name: Build and Deploy to cf-page Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies 📦
        run: npm i  --loglevel=info

      - name: Build 🏗️
        run: npm run build

      - name: Zip build folder 📦
        run: zip -r dist.zip ./dist

      - name: Upload build artifact 📤
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist.zip

      - name: Deploy to cf-page branch 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: cf-page
