name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
    - name: Build standalone
      run: npm run build-standalone-prod
    - name: Upload standalone artifact
      uses: actions/upload-artifact@v4
      with:
        name: standalone
        path: dist/standalone.html
    - name: Deploy to cf-page branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: cf-page
